# File introduces automated checks triggered on git events
# to enable run `pip install pre-commit && pre-commit install`

repos:

  # general checks (see here: https://pre-commit.com/hooks.html)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      -   id: trailing-whitespace
      -   id: check-docstring-first
      -   id: check-added-large-files
      -   id: debug-statements
      -   id: check-yaml
      -   id: check-merge-conflict
      -   id: end-of-file-fixer
      -   id: detect-private-key

  # yapf - the most OCD developer, following the most strict style guide
  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf

  # isort - sorting python imports
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  # flake8 - linting
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-builtins
          - flake8-coding
          - flake8-import-order
          - flake8-polyfill
          - flake8-quotes

  # helps you catch type-related errors in your code early, during
  # development, rather than at runtime
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
      - id: mypy
        additional_dependencies: [ types-requests, types-PyYAML, types-toml ]
